//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Common;

namespace AcadLib.Model.User.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAD_AutoCADEntities : DbContext
    {
        public CAD_AutoCADEntities()
            : base("name=CAD_AutoCADEntities")
        {
        }

        public CAD_AutoCADEntities(DbConnection con) : base(con, true)
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutocadUsers> AutocadUsers { get; set; }
    }
}
